# 프로그램 오류
- 오류는 시스템이 종료되어야 할 수준의 상황처럼 수습할 수 없는 심각한 문제를 의미함. 개발자가 미리 예측하여 방지할 수 없음
- 예외는 개발자가 구현한 로직에서 발생한 실수나 사용자의 조작에 의해 발생함. 오류와 달리 개발자가 미리 예측하여 방지할 수 있음(by.예외처리)
- 크게 컴파일 시점에서 발생하는 컴파일 에러와 프로그램 실행 도중에 발생하는 런타임 에러가 존재함
- 에러가 발생하면 프로그램의 비정상적 종료를 막을 수 없지만, 예외는 발생하더라도 프로그래머가 이에 대한 처리를 작성하여 프로그램의 비정상적인 종료를 막을 수 있음.
- 코드를 컴파일 할때 컴파일러가 코드에 대해 오타나 잘못된 구문, 자료형 체크 등의 기본적인 검사를 수행하여 오류가 있는지 알려줌
- 컴파일러가 알려준 에러들을 모두 수정해서 컴파일을 성공적으로 마친다고 에러가 발생하지 않는 것이 아님.(잠재적인 오류의 발생 가능성이 존재함)
- 자바에서는 Exception 예외처리를 통해 이런 예외의 경우들을 처리해야 함. 
![image](https://user-images.githubusercontent.com/69469529/188316825-5ac31b66-ef44-4d8c-88b9-4091992d2d79.png)
에러의 예로는 OutOfMemory나 StackOverflow가 있음

## Checked Exception
- 확인시점 : 컴파일 단계에서 확인
- 처리 : 반드시 예외를 처리해야 함
- 예외 발생시 트랜잭션 roll-back이 일어나지 않음
- Exception 하위 클래스 중 Runtime Exception을 제외한 모든 Exception
  - IOException
  - SQLException
  - FileNotFoundException

## Runtime(Unchecked) Exception
- 확인시점 : 실행 단계에서 확인
- 처리 : 명시적인 처리를 강제하지 않음
- 예외 발생시 트랜잭션 roll-back 발생
- Runtime Exception의 하위 클래스
  - NullPointerException
  - IndexOutOfBoundException
  - IllegalArgumentException
 
 ## 예외 처리 코드
- 자바 컴파일러는 컴파일할때 일반 예외가 발생할 가능성이 있는 코드를 발견하면 컴파일 오류를 발생시켜 개발자에게 강제로 예외 처리 코드 작성을 요구함.
- 실행 예외의 경우 컴파일러가 체크해주지 않기 때문에 예외 처리 코드를 개발자의 경험을 바탕으로 작성해야함
- try-catch 블록을 이용하여 해결
- try 블록 : 실제 코드의 위치, 예외가 발생할 가능성이 있는 코드
- catch 블록 : try 블록에서 예외 발생시 catch 로 이동하게 됨. 예외에 대한 처리 코드
- finally 블록 : try 블록의 예외 발생 유무와 상관없이 무조건 실행 되는 코드 (생략가능

 ## 예외처리의 2가지 방법
 ### 1. 내부에서 예외처리를 하는 경우 
 ``` JAVA
 void method1(){
    System.out.println("method1");
      try{
        throw new Exception();
      }
      catch(Exception e){
        System.out.println("Exception 발생");
      }
 }
 ```
 내부에서 예외처리를 하는 책임을 지고 있음
 
 ### 2. 메소드를 호출하는 쪽에서 예외 처리를 하는 경우
 ``` JAVA
 void method2 throws Exception(){
    System.out.println("method2");
    throw new Exception
 }
 ```
 이렇게 작성되는 경우는 단순히 코드의 로직만을 작성하고 호출하는 쪽에서 catch를 사용해서 책임을 회피한다.
 
 ``` JAVA
 try{
    method2();
 } catch(Exception e){
    System.out.println("Exception 발생");
 }
 ```
 
 ## 예외처리시 유의해야할 점
 1. 다중 catch문 처리
 ``` JAVA
 public class Main{
    public static void main(String[] args) {
        try{
            String[] strArr = null;
            for(int i=0;i<strArr.length;i++)
                System.out.println(strArr[i]);
        }catch(Exception e){
          e.printStackTrace();
          System.out.println("Exception Catch");
        }
        }catch(NullPointerException e){
            e.printStackTrace();
            System.out.println("NPE Exception Catch");
        }
    }
}
 ```
 다중 catch문에서 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 정상적인 동작을 할 수 있다.
 -> catch 블록의 동작인 위에서부터 처리되므로 위 코드와 같은 상황에선 NPE가 발생하였지만 NPE는 Exception의 하위 클래스이기 때문에 Exception Catch만이 출력될 것이다.
 
2. try-with-resources
``` JAVA
public static String getHtml(String url) throws IOException {

	URL targetUrl = new URL(url);

	try (BufferedReader reader = new BufferedReader(new InputStreamReader(targetUrl.openStream()))){
		StringBuffer html = new StringBuffer();
		String tmp;

		while ((tmp = reader.readLine()) != null) {
			html.append(tmp);
		}
		return html.toString();
	}
}
```
입출력이나 Connection과 관련된 코드에서 사용후엔 꼭 닫아줘야할 객체들이 존재하게 되는데 try-with-resources를 사용하여 try문안에 생성할 객체들을 선언해주면 try문을 벗어날때 자동적으로 close가 호출되므로 잘 활용할 수 있도록 하자.

